# Generated by Django 4.2.7 on 2024-04-29 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customer_profile_img_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraddress',
            name='default_address',
        ),
    ]
