# Generated by Django 4.2.7 on 2024-05-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_demo_url_product_product_file_product_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_file',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
